#!/bin/bash
set -x
qemu_exec=/home/mars/repo/qemu_ast6/build/qemu-system-arm
mmc_image=build/tmp/deploy/images/evb-mars/emmc.bin

slirpvde --dhcp &

$qemu_exec -M ast2600-evb,boot-emmc=true -m 1G -drive file=$mmc_image,format=raw,if=sd,index=2 -nodefaults -nographic  -serial  mon:stdio -qmp unix:$HOME/qmp.sock,server,nowait -net nic -net vde
